// imports
import { Inter } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Header from "./components/Header";
import NavBar from "./components/NavBar";
import Spacer from "./components/Spacer";

import { SP } from "next/dist/shared/lib/utils";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "CODEX EPICURIA",
//   // description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <div>
      <NavBar />
      <Spacer />
      <Header />
      <Spacer />
      <ToastContainer />
      <body className={inter.className}>{children}</body>
    </div>
  );
}
