DROP TABLE IF EXISTS steps CASCADE;
-- CREATE STEPS
CREATE TABLE steps (
  id SERIAL PRIMARY KEY, 
  recipe_id INTEGER REFERENCES recipes(id) ON DELETE CASCADE,
  step_number INTEGER NOT NULL,
  step_name VARCHAR(255),
  instructions TEXT
);
