DROP TABLE IF EXISTS favourites CASCADE;
-- CREATE FAVOURITES
CREATE TABLE favourites (
  id SERIAL PRIMARY KEY, 
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER REFERENCES recipes(id) ON DELETE CASCADE
);
