INSERT INTO measurements (measurement) VALUES ('mins');
INSERT INTO measurements (measurement) VALUES ('hrs');
INSERT INTO measurements (measurement) VALUES ('cup');
INSERT INTO measurements (measurement) VALUES ('ml');
INSERT INTO measurements (measurement) VALUES ('L');
INSERT INTO measurements (measurement) VALUES ('g');
INSERT INTO measurements (measurement) VALUES ('mg');
INSERT INTO measurements (measurement) VALUES ('tbsp');
INSERT INTO measurements (measurement) VALUES ('tsp');
INSERT INTO measurements (measurement) VALUES ('pt');
INSERT INTO measurements (measurement) VALUES ('qt');
INSERT INTO measurements (measurement) VALUES ('lb');
INSERT INTO measurements (measurement) VALUES ('oz');
INSERT INTO measurements (measurement) VALUES ('fl oz');
INSERT INTO measurements (measurement) VALUES ('packet');
INSERT INTO measurements (measurement) VALUES ('-');
INSERT INTO measurements (measurement) VALUES ('for serving');
INSERT INTO measurements (measurement) VALUES ('to taste');
