-- Seed tags
INSERT INTO tags (tag) VALUES ('soups');
INSERT INTO tags (tag) VALUES ('vegan');
INSERT INTO tags (tag) VALUES ('Italian');
INSERT INTO tags (tag) VALUES ('seafood');
INSERT INTO tags (tag) VALUES ('hearty');
INSERT INTO tags (tag) VALUES ('pasta');
INSERT INTO tags (tag) VALUES ('creamy');
INSERT INTO tags (tag) VALUES ('spicy');
INSERT INTO tags (tag) VALUES ('tomato-sauce');
INSERT INTO tags (tag) VALUES ('chicken');
INSERT INTO tags (tag) VALUES ('30 minutes or less');
INSERT INTO tags (tag) VALUES ('appetizers');
INSERT INTO tags (tag) VALUES ('serves 4-6');
INSERT INTO tags (tag) VALUES ('healthy');
INSERT INTO tags (tag) VALUES ('asian');
INSERT INTO tags (tag) VALUES ('mexican');
INSERT INTO tags (tag) VALUES ('desserts');
INSERT INTO tags (tag) VALUES ('breakfast');
INSERT INTO tags (tag) VALUES ('lunch');
INSERT INTO tags (tag) VALUES ('dinner');