-- Seed ingredients
INSERT INTO ingredients (ingredient) VALUES ('black pepper');
INSERT INTO ingredients (ingredient) VALUES ('garlic salt');
INSERT INTO ingredients (ingredient) VALUES ('chicken stock base');
INSERT INTO ingredients (ingredient) VALUES ('butter');
INSERT INTO ingredients (ingredient) VALUES ('celery');
INSERT INTO ingredients (ingredient) VALUES ('onion');
INSERT INTO ingredients (ingredient) VALUES ('potatoes'); 
INSERT INTO ingredients (ingredient) VALUES ('carrots');
INSERT INTO ingredients (ingredient) VALUES ('tomato'); 
INSERT INTO ingredients (ingredient) VALUES ('orzo');
INSERT INTO ingredients (ingredient) VALUES ('cooked chicken');
INSERT INTO ingredients (ingredient) VALUES ('spicy chorizo');
INSERT INTO ingredients (ingredient) VALUES ('water');
INSERT INTO ingredients (ingredient) VALUES ('pimenta moida (portuguese ground pepper paste)');
INSERT INTO ingredients (ingredient) VALUES ('all-purpose flour');
INSERT INTO ingredients (ingredient) VALUES ('extra-virgin olive oil');
INSERT INTO ingredients (ingredient) VALUES ('dried oregano');
INSERT INTO ingredients (ingredient) VALUES ('garlic cloves, chopped');
INSERT INTO ingredients (ingredient) VALUES ('tomato paste');
INSERT INTO ingredients (ingredient) VALUES ('chicken stock');
INSERT INTO ingredients (ingredient) VALUES ('heavy cream');
INSERT INTO ingredients (ingredient) VALUES ('grated Parmesan');
INSERT INTO ingredients (ingredient) VALUES ('sun-dried totoes packed in oil');
INSERT INTO ingredients (ingredient) VALUES ('fresh basil');
INSERT INTO ingredients (ingredient) VALUES ('chicken breasts');
INSERT INTO ingredients (ingredient) VALUES ('shredded kale');
INSERT INTO ingredients (ingredient) VALUES ('mini potatoes');
INSERT INTO ingredients (ingredient) VALUES ('Italian sausage');
INSERT INTO ingredients (ingredient) VALUES ('red-pepper flakes');
INSERT INTO ingredients (ingredient) VALUES ('Knorr alfredo packet');
INSERT INTO ingredients (ingredient) VALUES ('18% cream');
INSERT INTO ingredients (ingredient) VALUES ('dried parsley');
INSERT INTO ingredients (ingredient) VALUES ('cajun spice');
INSERT INTO ingredients (ingredient) VALUES ('Montreal Steak Spice');
INSERT INTO ingredients (ingredient) VALUES ('Farfalle pasta');
INSERT INTO ingredients (ingredient) VALUES ('minced garlic');
INSERT INTO ingredients (ingredient) VALUES ('mild Italian sausage');
INSERT INTO ingredients (ingredient) VALUES ('kosher salt');
INSERT INTO ingredients (ingredient) VALUES ('chicken thighs');
INSERT INTO ingredients (ingredient) VALUES ('paprika');
INSERT INTO ingredients (ingredient) VALUES ('peas');
INSERT INTO ingredients (ingredient) VALUES ('salt');
